Iter1
bbquite/go-loyalty pull request #2
Opened 2024-10-31 11:38 UTC by bbquite

2024-11-01 17:10 UTC, nburunova commented
не прошли statictest, посмотри, пожалуйста, что там за проблемы

2024-11-01 17:32 UTC, nburunova requested changes

2024-11-01 17:32 UTC, nburunova commented on internal/api/api.go
> +package api
может пакет и файл назовем AccuralClient? иначе не сразу понятно, что за апи тут

2024-11-01 17:32 UTC, nburunova commented on internal/app/app.go
> +		for {
тут еще надо закрыть канал purchasesQueue, когда из функции-писателя в канал выходим, чтобы горуина checkPurchaseIsCalculated завершилась

2024-11-01 17:32 UTC, nburunova commented on internal/storage/database.go
> +	ctx     context.Context
контекст нельзя хранить в поле структуры, ctx должен быть первым аргументом в методах DBStorage 
Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx: https://pkg.go.dev/context

2024-11-01 17:32 UTC, nburunova commented on pkg/xretry/xretry.go
> +	// err := immediatelyRetry(f, r.p.immediateRetries)
закомментированный код советую убрать, репозиторий должен быть чистым от лишнего

2024-11-01 18:23 UTC, bbquite commented on pkg/xretry/xretry.go
> +	// err := immediatelyRetry(f, r.p.immediateRetries)
done

2024-11-01 18:29 UTC, bbquite commented on internal/api/api.go
> +package api
done

2024-11-01 18:33 UTC, bbquite commented on internal/app/app.go
> +		for {
done

2024-11-01 18:47 UTC, bbquite commented on internal/storage/database.go
> +	ctx     context.Context
done

2024-11-03 17:09 UTC, nburunova approved these changes

2024-11-03 17:16 UTC, merged